### ISSUE TITLE
PHP error in debug.log

### ISSUE THREAD

**Issue by calvintam236** [ank91/ank-simplified-ga#1]
It is running on the latest version of the plugin (v0.9.5). It has been in the log for months.. Can you fix it?
`[27-Oct-2015 18:44:19 UTC] PHP Notice:  Undefined index: tab in /home/xxxxxxxxxx/public_html/wp-content/plugins/enhanced-e-commerce-for-woocommerce-store/includes/class-wc-enhanced-ecommerce-google-analytics-integration.php on line 1118`

**Comment by ankurk91** [comment]
This bug is not related to my plugin (ank-simplified-ga).
Please contact the author of this plugin.

FYI, This bug is has been already reported [here](https://wordpress.org/support/topic/php-warning-on-backend)
